language: generic

env:
  global:
    - PYMODULE: r3py
    - RELEASE_PYTHON_VERSIONS: "2.7 3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: r3py
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: stretch
      sudo: false
      language: python
      python: "2.7.13"
      services: [docker]
      env:
        - BUILD=wheels,release
        - PYTHON_VERSION=2.7.13
      before_install:
        - sudo add-apt-repository ppa:r3-team/libr3-daily -y
        - sudo apt-get update -q
        - sudo apt-get install libr3

      install:
        - make
