language: generic

env:
  global:
    - PYMODULE: r3py
    - RELEASE_PYTHON_VERSIONS: "2.7 3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: r3py
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    - CIBW_BEFORE_BUILD="sh -c 'pip install cython && make'"
    - CIBW_SKIP="cp26-* cp33-* cp34*"
    - CIBW_OUPUT_DIR="dist/"

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: stretch
      sudo: false
      language: python
      python: "2.7.13"
      services: [docker]
      env:
        - PLATFORM=linux
      #before_install:
      #  - sudo add-apt-repository ppa:r3-team/libr3-daily -y
      #  - sudo apt-get update -q
      #  - sudo apt-get install -y libr3-dev
      addons:
        apt:
          sources:
            - sourceline: 'deb http://ppa.launchpad.net/r3-team/libr3-daily/ubuntu trusty main '
            - sourceline: 'deb-src http://ppa.launchpad.net/r3-team/libr3-daily/ubuntu trusty main '
          packages:
            - libr3-dev
            - libpcre3-dev
            
cache:
  pip

install:
  - pip install pip --upgrade
  - pip install cython
  - pip install cibuildwheel

script:
  - make
  #- cibuildwheel --platform $PLATFORM --output-dir $CIBW_OUPUT_DIR
