language: generic

env:
  global:
    - PYMODULE: r3py
    - RELEASE_PYTHON_VERSIONS: "2.7 3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: r3py
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      sudo: false
      language: python
      python: "2.7.13"
      services: [docker]
      env: BUILD=wheels,release PYTHON_VERSION=2.7.13

    - os: linux
      dist: xenial
      sudo: false
      language: python
      python: "3.5.3"
      services: [docker]
      env: BUILD=wheels,release PYTHON_VERSION=3.5.3

    - os: linux
      dist: xenial
      sudo: false
      language: python
      python: "3.6.1"
      services: [docker]
      env: BUILD=wheels,release PYTHON_VERSION=3.6.1

cache:
  pip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libr3-dev libr3-0

install:
  - pip install --upgrade pip
  - pip install cython

script:
  - pip install cython
  - make
